name: Datamovement
channels:
  - conda-forge
dependencies:
  - python=3.9 
  - pip
  - pip:    
    - azure-storage-blob==12.11.0
    - azure-storage-file-share==12.7.0
    - azure-storage-file==2.1.0
    - azure-data-tables==12.0.0  
    - azure.identity==1.7.0
    - requests==2.27.1
